// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

@com.google.protobuf.Generated
public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flux.wire.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.flux.wire.AppendRequest append = 1;</code>
   * @return Whether the append field is set.
   */
  boolean hasAppend();
  /**
   * <code>.flux.wire.AppendRequest append = 1;</code>
   * @return The append.
   */
  io.flux.sdk.proto.AppendRequest getAppend();
  /**
   * <code>.flux.wire.AppendRequest append = 1;</code>
   */
  io.flux.sdk.proto.AppendRequestOrBuilder getAppendOrBuilder();

  /**
   * <code>.flux.wire.ReadRequest read = 2;</code>
   * @return Whether the read field is set.
   */
  boolean hasRead();
  /**
   * <code>.flux.wire.ReadRequest read = 2;</code>
   * @return The read.
   */
  io.flux.sdk.proto.ReadRequest getRead();
  /**
   * <code>.flux.wire.ReadRequest read = 2;</code>
   */
  io.flux.sdk.proto.ReadRequestOrBuilder getReadOrBuilder();

  /**
   * <code>.flux.wire.JoinGroupRequest join_group = 3;</code>
   * @return Whether the joinGroup field is set.
   */
  boolean hasJoinGroup();
  /**
   * <code>.flux.wire.JoinGroupRequest join_group = 3;</code>
   * @return The joinGroup.
   */
  io.flux.sdk.proto.JoinGroupRequest getJoinGroup();
  /**
   * <code>.flux.wire.JoinGroupRequest join_group = 3;</code>
   */
  io.flux.sdk.proto.JoinGroupRequestOrBuilder getJoinGroupOrBuilder();

  /**
   * <code>.flux.wire.HeartbeatRequest heartbeat = 4;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.flux.wire.HeartbeatRequest heartbeat = 4;</code>
   * @return The heartbeat.
   */
  io.flux.sdk.proto.HeartbeatRequest getHeartbeat();
  /**
   * <code>.flux.wire.HeartbeatRequest heartbeat = 4;</code>
   */
  io.flux.sdk.proto.HeartbeatRequestOrBuilder getHeartbeatOrBuilder();

  /**
   * <code>.flux.wire.PollRequest poll = 5;</code>
   * @return Whether the poll field is set.
   */
  boolean hasPoll();
  /**
   * <code>.flux.wire.PollRequest poll = 5;</code>
   * @return The poll.
   */
  io.flux.sdk.proto.PollRequest getPoll();
  /**
   * <code>.flux.wire.PollRequest poll = 5;</code>
   */
  io.flux.sdk.proto.PollRequestOrBuilder getPollOrBuilder();

  /**
   * <code>.flux.wire.LeaveGroupRequest leave_group = 6;</code>
   * @return Whether the leaveGroup field is set.
   */
  boolean hasLeaveGroup();
  /**
   * <code>.flux.wire.LeaveGroupRequest leave_group = 6;</code>
   * @return The leaveGroup.
   */
  io.flux.sdk.proto.LeaveGroupRequest getLeaveGroup();
  /**
   * <code>.flux.wire.LeaveGroupRequest leave_group = 6;</code>
   */
  io.flux.sdk.proto.LeaveGroupRequestOrBuilder getLeaveGroupOrBuilder();

  /**
   * <code>.flux.wire.CommitRequest commit = 7;</code>
   * @return Whether the commit field is set.
   */
  boolean hasCommit();
  /**
   * <code>.flux.wire.CommitRequest commit = 7;</code>
   * @return The commit.
   */
  io.flux.sdk.proto.CommitRequest getCommit();
  /**
   * <code>.flux.wire.CommitRequest commit = 7;</code>
   */
  io.flux.sdk.proto.CommitRequestOrBuilder getCommitOrBuilder();

  /**
   * <code>.flux.wire.AuthRequest auth = 8;</code>
   * @return Whether the auth field is set.
   */
  boolean hasAuth();
  /**
   * <code>.flux.wire.AuthRequest auth = 8;</code>
   * @return The auth.
   */
  io.flux.sdk.proto.AuthRequest getAuth();
  /**
   * <code>.flux.wire.AuthRequest auth = 8;</code>
   */
  io.flux.sdk.proto.AuthRequestOrBuilder getAuthOrBuilder();

  /**
   * <code>.flux.wire.RawReadRequest raw_read = 9;</code>
   * @return Whether the rawRead field is set.
   */
  boolean hasRawRead();
  /**
   * <code>.flux.wire.RawReadRequest raw_read = 9;</code>
   * @return The rawRead.
   */
  io.flux.sdk.proto.RawReadRequest getRawRead();
  /**
   * <code>.flux.wire.RawReadRequest raw_read = 9;</code>
   */
  io.flux.sdk.proto.RawReadRequestOrBuilder getRawReadOrBuilder();

  io.flux.sdk.proto.ClientMessage.MessageCase getMessageCase();
}
