// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

@com.google.protobuf.Generated
public final class FluxWire extends com.google.protobuf.GeneratedFile {
  private FluxWire() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "FluxWire");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_RecordBatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_RecordBatch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_BatchAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_BatchAck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_AppendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_AppendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_AppendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_AppendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_TopicResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_TopicResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_ReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_RawReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_RawReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_RawSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_RawSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_RawReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_RawReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_JoinGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_JoinGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_JoinGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_JoinGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_PollRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_PollRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_PollResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_PollResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_LeaveGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_LeaveGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_LeaveGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_LeaveGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_CommitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_AuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_AuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flux_wire_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flux_wire_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017flux_wire.proto\022\tflux.wire\"1\n\006Record\022\020" +
      "\n\003key\030\001 \001(\014H\000\210\001\001\022\r\n\005value\030\002 \001(\014B\006\n\004_key\"" +
      "V\n\013RecordBatch\022\020\n\010topic_id\030\001 \001(\r\022\021\n\tsche" +
      "ma_id\030\002 \001(\r\022\"\n\007records\030\003 \003(\0132\021.flux.wire" +
      ".Record\"Y\n\010BatchAck\022\020\n\010topic_id\030\001 \001(\r\022\021\n" +
      "\tschema_id\030\002 \001(\r\022\024\n\014start_offset\030\003 \001(\004\022\022" +
      "\n\nend_offset\030\004 \001(\004\"_\n\rAppendRequest\022\021\n\tw" +
      "riter_id\030\001 \001(\014\022\022\n\nappend_seq\030\002 \001(\004\022\'\n\007ba" +
      "tches\030\003 \003(\0132\026.flux.wire.RecordBatch\"\212\001\n\016" +
      "AppendResponse\022\022\n\nappend_seq\030\001 \001(\004\022\017\n\007su" +
      "ccess\030\002 \001(\010\022\022\n\nerror_code\030\003 \001(\r\022\025\n\rerror" +
      "_message\030\004 \001(\t\022(\n\013append_acks\030\005 \003(\0132\023.fl" +
      "ux.wire.BatchAck\"B\n\013ReadRequest\022\020\n\010topic" +
      "_id\030\001 \001(\r\022\016\n\006offset\030\002 \001(\004\022\021\n\tmax_bytes\030\003" +
      " \001(\r\"n\n\013TopicResult\022\020\n\010topic_id\030\001 \001(\r\022\021\n" +
      "\tschema_id\030\002 \001(\r\022\026\n\016high_watermark\030\003 \001(\004" +
      "\022\"\n\007records\030\004 \003(\0132\021.flux.wire.Record\"s\n\014" +
      "ReadResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nerror_c" +
      "ode\030\002 \001(\r\022\025\n\rerror_message\030\003 \001(\t\022\'\n\007resu" +
      "lts\030\004 \003(\0132\026.flux.wire.TopicResult\"E\n\016Raw" +
      "ReadRequest\022\020\n\010topic_id\030\001 \001(\r\022\016\n\006offset\030" +
      "\002 \001(\004\022\021\n\tmax_bytes\030\003 \001(\r\"{\n\nRawSegment\022\020" +
      "\n\010topic_id\030\001 \001(\r\022\021\n\tschema_id\030\002 \001(\r\022\024\n\014s" +
      "tart_offset\030\003 \001(\004\022\022\n\nend_offset\030\004 \001(\004\022\r\n" +
      "\005crc32\030\005 \001(\r\022\017\n\007payload\030\006 \001(\014\"\216\001\n\017RawRea" +
      "dResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nerror_code" +
      "\030\002 \001(\r\022\025\n\rerror_message\030\003 \001(\t\022\026\n\016high_wa" +
      "termark\030\004 \001(\004\022\'\n\010segments\030\005 \003(\0132\025.flux.w" +
      "ire.RawSegment\"J\n\020JoinGroupRequest\022\020\n\010gr" +
      "oup_id\030\001 \001(\t\022\021\n\treader_id\030\002 \001(\t\022\021\n\ttopic" +
      "_ids\030\003 \003(\r\"O\n\021JoinGroupResponse\022\017\n\007succe" +
      "ss\030\001 \001(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rerror_me" +
      "ssage\030\003 \001(\t\"I\n\020HeartbeatRequest\022\020\n\010group" +
      "_id\030\001 \001(\t\022\020\n\010topic_id\030\002 \001(\r\022\021\n\treader_id" +
      "\030\003 \001(\t\"{\n\021HeartbeatResponse\022\017\n\007success\030\001" +
      " \001(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rerror_messag" +
      "e\030\003 \001(\t\022*\n\006status\030\004 \001(\0162\032.flux.wire.Hear" +
      "tbeatStatus\"W\n\013PollRequest\022\020\n\010group_id\030\001" +
      " \001(\t\022\020\n\010topic_id\030\002 \001(\r\022\021\n\treader_id\030\003 \001(" +
      "\t\022\021\n\tmax_bytes\030\004 \001(\r\"\270\001\n\014PollResponse\022\017\n" +
      "\007success\030\001 \001(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rer" +
      "ror_message\030\003 \001(\t\022\'\n\007results\030\004 \003(\0132\026.flu" +
      "x.wire.TopicResult\022\024\n\014start_offset\030\005 \001(\004" +
      "\022\022\n\nend_offset\030\006 \001(\004\022\031\n\021lease_deadline_m" +
      "s\030\007 \001(\004\"J\n\021LeaveGroupRequest\022\020\n\010group_id" +
      "\030\001 \001(\t\022\020\n\010topic_id\030\002 \001(\r\022\021\n\treader_id\030\003 " +
      "\001(\t\"P\n\022LeaveGroupResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rerror_message\030" +
      "\003 \001(\t\"p\n\rCommitRequest\022\020\n\010group_id\030\001 \001(\t" +
      "\022\021\n\treader_id\030\002 \001(\t\022\020\n\010topic_id\030\003 \001(\r\022\024\n" +
      "\014start_offset\030\004 \001(\004\022\022\n\nend_offset\030\005 \001(\004\"" +
      "L\n\016CommitResponse\022\017\n\007success\030\001 \001(\010\022\022\n\ner" +
      "ror_code\030\002 \001(\r\022\025\n\rerror_message\030\003 \001(\t\"\036\n" +
      "\013AuthRequest\022\017\n\007api_key\030\001 \001(\t\"J\n\014AuthRes" +
      "ponse\022\017\n\007success\030\001 \001(\010\022\022\n\nerror_code\030\002 \001" +
      "(\r\022\025\n\rerror_message\030\003 \001(\t\"\263\003\n\rClientMess" +
      "age\022*\n\006append\030\001 \001(\0132\030.flux.wire.AppendRe" +
      "questH\000\022&\n\004read\030\002 \001(\0132\026.flux.wire.ReadRe" +
      "questH\000\0221\n\njoin_group\030\003 \001(\0132\033.flux.wire." +
      "JoinGroupRequestH\000\0220\n\theartbeat\030\004 \001(\0132\033." +
      "flux.wire.HeartbeatRequestH\000\022&\n\004poll\030\005 \001" +
      "(\0132\026.flux.wire.PollRequestH\000\0223\n\013leave_gr" +
      "oup\030\006 \001(\0132\034.flux.wire.LeaveGroupRequestH" +
      "\000\022*\n\006commit\030\007 \001(\0132\030.flux.wire.CommitRequ" +
      "estH\000\022&\n\004auth\030\010 \001(\0132\026.flux.wire.AuthRequ" +
      "estH\000\022-\n\010raw_read\030\t \001(\0132\031.flux.wire.RawR" +
      "eadRequestH\000B\t\n\007message\"\274\003\n\rServerMessag" +
      "e\022+\n\006append\030\001 \001(\0132\031.flux.wire.AppendResp" +
      "onseH\000\022\'\n\004read\030\002 \001(\0132\027.flux.wire.ReadRes" +
      "ponseH\000\0222\n\njoin_group\030\003 \001(\0132\034.flux.wire." +
      "JoinGroupResponseH\000\0221\n\theartbeat\030\004 \001(\0132\034" +
      ".flux.wire.HeartbeatResponseH\000\022\'\n\004poll\030\005" +
      " \001(\0132\027.flux.wire.PollResponseH\000\0224\n\013leave" +
      "_group\030\006 \001(\0132\035.flux.wire.LeaveGroupRespo" +
      "nseH\000\022+\n\006commit\030\007 \001(\0132\031.flux.wire.Commit" +
      "ResponseH\000\022\'\n\004auth\030\010 \001(\0132\027.flux.wire.Aut" +
      "hResponseH\000\022.\n\010raw_read\030\t \001(\0132\032.flux.wir" +
      "e.RawReadResponseH\000B\t\n\007message*O\n\017Heartb" +
      "eatStatus\022\027\n\023HEARTBEAT_STATUS_OK\020\000\022#\n\037HE" +
      "ARTBEAT_STATUS_UNKNOWN_MEMBER\020\001B\025\n\021io.fl" +
      "ux.sdk.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_flux_wire_Record_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_flux_wire_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_Record_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_flux_wire_RecordBatch_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_flux_wire_RecordBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_RecordBatch_descriptor,
        new java.lang.String[] { "TopicId", "SchemaId", "Records", });
    internal_static_flux_wire_BatchAck_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_flux_wire_BatchAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_BatchAck_descriptor,
        new java.lang.String[] { "TopicId", "SchemaId", "StartOffset", "EndOffset", });
    internal_static_flux_wire_AppendRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_flux_wire_AppendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_AppendRequest_descriptor,
        new java.lang.String[] { "WriterId", "AppendSeq", "Batches", });
    internal_static_flux_wire_AppendResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_flux_wire_AppendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_AppendResponse_descriptor,
        new java.lang.String[] { "AppendSeq", "Success", "ErrorCode", "ErrorMessage", "AppendAcks", });
    internal_static_flux_wire_ReadRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_flux_wire_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_ReadRequest_descriptor,
        new java.lang.String[] { "TopicId", "Offset", "MaxBytes", });
    internal_static_flux_wire_TopicResult_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_flux_wire_TopicResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_TopicResult_descriptor,
        new java.lang.String[] { "TopicId", "SchemaId", "HighWatermark", "Records", });
    internal_static_flux_wire_ReadResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_flux_wire_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_ReadResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Results", });
    internal_static_flux_wire_RawReadRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_flux_wire_RawReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_RawReadRequest_descriptor,
        new java.lang.String[] { "TopicId", "Offset", "MaxBytes", });
    internal_static_flux_wire_RawSegment_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_flux_wire_RawSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_RawSegment_descriptor,
        new java.lang.String[] { "TopicId", "SchemaId", "StartOffset", "EndOffset", "Crc32", "Payload", });
    internal_static_flux_wire_RawReadResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_flux_wire_RawReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_RawReadResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "HighWatermark", "Segments", });
    internal_static_flux_wire_JoinGroupRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_flux_wire_JoinGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_JoinGroupRequest_descriptor,
        new java.lang.String[] { "GroupId", "ReaderId", "TopicIds", });
    internal_static_flux_wire_JoinGroupResponse_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_flux_wire_JoinGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_JoinGroupResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_flux_wire_HeartbeatRequest_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_flux_wire_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_HeartbeatRequest_descriptor,
        new java.lang.String[] { "GroupId", "TopicId", "ReaderId", });
    internal_static_flux_wire_HeartbeatResponse_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_flux_wire_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Status", });
    internal_static_flux_wire_PollRequest_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_flux_wire_PollRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_PollRequest_descriptor,
        new java.lang.String[] { "GroupId", "TopicId", "ReaderId", "MaxBytes", });
    internal_static_flux_wire_PollResponse_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_flux_wire_PollResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_PollResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Results", "StartOffset", "EndOffset", "LeaseDeadlineMs", });
    internal_static_flux_wire_LeaveGroupRequest_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_flux_wire_LeaveGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_LeaveGroupRequest_descriptor,
        new java.lang.String[] { "GroupId", "TopicId", "ReaderId", });
    internal_static_flux_wire_LeaveGroupResponse_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_flux_wire_LeaveGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_LeaveGroupResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_flux_wire_CommitRequest_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_flux_wire_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_CommitRequest_descriptor,
        new java.lang.String[] { "GroupId", "ReaderId", "TopicId", "StartOffset", "EndOffset", });
    internal_static_flux_wire_CommitResponse_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_flux_wire_CommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_CommitResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_flux_wire_AuthRequest_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_flux_wire_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_AuthRequest_descriptor,
        new java.lang.String[] { "ApiKey", });
    internal_static_flux_wire_AuthResponse_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_flux_wire_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_AuthResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_flux_wire_ClientMessage_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_flux_wire_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_ClientMessage_descriptor,
        new java.lang.String[] { "Append", "Read", "JoinGroup", "Heartbeat", "Poll", "LeaveGroup", "Commit", "Auth", "RawRead", "Message", });
    internal_static_flux_wire_ServerMessage_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_flux_wire_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flux_wire_ServerMessage_descriptor,
        new java.lang.String[] { "Append", "Read", "JoinGroup", "Heartbeat", "Poll", "LeaveGroup", "Commit", "Auth", "RawRead", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
