// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

/**
 * <pre>
 * Zero-copy read: the broker returns compressed FL segments as-is;
 * the client decompresses and decodes records locally.
 * </pre>
 *
 * Protobuf type {@code flux.wire.RawReadRequest}
 */
@com.google.protobuf.Generated
public final class RawReadRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flux.wire.RawReadRequest)
    RawReadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RawReadRequest");
  }
  // Use RawReadRequest.newBuilder() to construct.
  private RawReadRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RawReadRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawReadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawReadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flux.sdk.proto.RawReadRequest.class, io.flux.sdk.proto.RawReadRequest.Builder.class);
  }

  public static final int TOPIC_ID_FIELD_NUMBER = 1;
  private int topicId_ = 0;
  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  @java.lang.Override
  public int getTopicId() {
    return topicId_;
  }

  public static final int OFFSET_FIELD_NUMBER = 2;
  private long offset_ = 0L;
  /**
   * <code>uint64 offset = 2;</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int MAX_BYTES_FIELD_NUMBER = 3;
  private int maxBytes_ = 0;
  /**
   * <pre>
   * Budget in *compressed* bytes.
   * </pre>
   *
   * <code>uint32 max_bytes = 3;</code>
   * @return The maxBytes.
   */
  @java.lang.Override
  public int getMaxBytes() {
    return maxBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (topicId_ != 0) {
      output.writeUInt32(1, topicId_);
    }
    if (offset_ != 0L) {
      output.writeUInt64(2, offset_);
    }
    if (maxBytes_ != 0) {
      output.writeUInt32(3, maxBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (topicId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, topicId_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, offset_);
    }
    if (maxBytes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, maxBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flux.sdk.proto.RawReadRequest)) {
      return super.equals(obj);
    }
    io.flux.sdk.proto.RawReadRequest other = (io.flux.sdk.proto.RawReadRequest) obj;

    if (getTopicId()
        != other.getTopicId()) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (getMaxBytes()
        != other.getMaxBytes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + MAX_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxBytes();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flux.sdk.proto.RawReadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flux.sdk.proto.RawReadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flux.sdk.proto.RawReadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flux.sdk.proto.RawReadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Zero-copy read: the broker returns compressed FL segments as-is;
   * the client decompresses and decodes records locally.
   * </pre>
   *
   * Protobuf type {@code flux.wire.RawReadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flux.wire.RawReadRequest)
      io.flux.sdk.proto.RawReadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawReadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawReadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flux.sdk.proto.RawReadRequest.class, io.flux.sdk.proto.RawReadRequest.Builder.class);
    }

    // Construct using io.flux.sdk.proto.RawReadRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topicId_ = 0;
      offset_ = 0L;
      maxBytes_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawReadRequest_descriptor;
    }

    @java.lang.Override
    public io.flux.sdk.proto.RawReadRequest getDefaultInstanceForType() {
      return io.flux.sdk.proto.RawReadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.flux.sdk.proto.RawReadRequest build() {
      io.flux.sdk.proto.RawReadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flux.sdk.proto.RawReadRequest buildPartial() {
      io.flux.sdk.proto.RawReadRequest result = new io.flux.sdk.proto.RawReadRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.flux.sdk.proto.RawReadRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.topicId_ = topicId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.offset_ = offset_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxBytes_ = maxBytes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flux.sdk.proto.RawReadRequest) {
        return mergeFrom((io.flux.sdk.proto.RawReadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flux.sdk.proto.RawReadRequest other) {
      if (other == io.flux.sdk.proto.RawReadRequest.getDefaultInstance()) return this;
      if (other.getTopicId() != 0) {
        setTopicId(other.getTopicId());
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (other.getMaxBytes() != 0) {
        setMaxBytes(other.getMaxBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              topicId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              offset_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              maxBytes_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int topicId_ ;
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return The topicId.
     */
    @java.lang.Override
    public int getTopicId() {
      return topicId_;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @param value The topicId to set.
     * @return This builder for chaining.
     */
    public Builder setTopicId(int value) {

      topicId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      topicId_ = 0;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <code>uint64 offset = 2;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>uint64 offset = 2;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {

      offset_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 offset = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000002);
      offset_ = 0L;
      onChanged();
      return this;
    }

    private int maxBytes_ ;
    /**
     * <pre>
     * Budget in *compressed* bytes.
     * </pre>
     *
     * <code>uint32 max_bytes = 3;</code>
     * @return The maxBytes.
     */
    @java.lang.Override
    public int getMaxBytes() {
      return maxBytes_;
    }
    /**
     * <pre>
     * Budget in *compressed* bytes.
     * </pre>
     *
     * <code>uint32 max_bytes = 3;</code>
     * @param value The maxBytes to set.
     * @return This builder for chaining.
     */
    public Builder setMaxBytes(int value) {

      maxBytes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Budget in *compressed* bytes.
     * </pre>
     *
     * <code>uint32 max_bytes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxBytes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxBytes_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flux.wire.RawReadRequest)
  }

  // @@protoc_insertion_point(class_scope:flux.wire.RawReadRequest)
  private static final io.flux.sdk.proto.RawReadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flux.sdk.proto.RawReadRequest();
  }

  public static io.flux.sdk.proto.RawReadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RawReadRequest>
      PARSER = new com.google.protobuf.AbstractParser<RawReadRequest>() {
    @java.lang.Override
    public RawReadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RawReadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RawReadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flux.sdk.proto.RawReadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

