// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

@com.google.protobuf.Generated
public interface RawReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flux.wire.RawReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>uint64 offset = 2;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <pre>
   * Budget in *compressed* bytes.
   * </pre>
   *
   * <code>uint32 max_bytes = 3;</code>
   * @return The maxBytes.
   */
  int getMaxBytes();
}
