// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

@com.google.protobuf.Generated
public interface RawSegmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flux.wire.RawSegment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>uint32 schema_id = 2;</code>
   * @return The schemaId.
   */
  int getSchemaId();

  /**
   * <code>uint64 start_offset = 3;</code>
   * @return The startOffset.
   */
  long getStartOffset();

  /**
   * <code>uint64 end_offset = 4;</code>
   * @return The endOffset.
   */
  long getEndOffset();

  /**
   * <code>uint32 crc32 = 5;</code>
   * @return The crc32.
   */
  int getCrc32();

  /**
   * <pre>
   * Compressed FL segment payload (zstd).
   * </pre>
   *
   * <code>bytes payload = 6;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
