// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

/**
 * Protobuf type {@code flux.wire.RawSegment}
 */
@com.google.protobuf.Generated
public final class RawSegment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flux.wire.RawSegment)
    RawSegmentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RawSegment");
  }
  // Use RawSegment.newBuilder() to construct.
  private RawSegment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RawSegment() {
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawSegment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawSegment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flux.sdk.proto.RawSegment.class, io.flux.sdk.proto.RawSegment.Builder.class);
  }

  public static final int TOPIC_ID_FIELD_NUMBER = 1;
  private int topicId_ = 0;
  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  @java.lang.Override
  public int getTopicId() {
    return topicId_;
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 2;
  private int schemaId_ = 0;
  /**
   * <code>uint32 schema_id = 2;</code>
   * @return The schemaId.
   */
  @java.lang.Override
  public int getSchemaId() {
    return schemaId_;
  }

  public static final int START_OFFSET_FIELD_NUMBER = 3;
  private long startOffset_ = 0L;
  /**
   * <code>uint64 start_offset = 3;</code>
   * @return The startOffset.
   */
  @java.lang.Override
  public long getStartOffset() {
    return startOffset_;
  }

  public static final int END_OFFSET_FIELD_NUMBER = 4;
  private long endOffset_ = 0L;
  /**
   * <code>uint64 end_offset = 4;</code>
   * @return The endOffset.
   */
  @java.lang.Override
  public long getEndOffset() {
    return endOffset_;
  }

  public static final int CRC32_FIELD_NUMBER = 5;
  private int crc32_ = 0;
  /**
   * <code>uint32 crc32 = 5;</code>
   * @return The crc32.
   */
  @java.lang.Override
  public int getCrc32() {
    return crc32_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Compressed FL segment payload (zstd).
   * </pre>
   *
   * <code>bytes payload = 6;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (topicId_ != 0) {
      output.writeUInt32(1, topicId_);
    }
    if (schemaId_ != 0) {
      output.writeUInt32(2, schemaId_);
    }
    if (startOffset_ != 0L) {
      output.writeUInt64(3, startOffset_);
    }
    if (endOffset_ != 0L) {
      output.writeUInt64(4, endOffset_);
    }
    if (crc32_ != 0) {
      output.writeUInt32(5, crc32_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(6, payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (topicId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, topicId_);
    }
    if (schemaId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, schemaId_);
    }
    if (startOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, startOffset_);
    }
    if (endOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, endOffset_);
    }
    if (crc32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, crc32_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flux.sdk.proto.RawSegment)) {
      return super.equals(obj);
    }
    io.flux.sdk.proto.RawSegment other = (io.flux.sdk.proto.RawSegment) obj;

    if (getTopicId()
        != other.getTopicId()) return false;
    if (getSchemaId()
        != other.getSchemaId()) return false;
    if (getStartOffset()
        != other.getStartOffset()) return false;
    if (getEndOffset()
        != other.getEndOffset()) return false;
    if (getCrc32()
        != other.getCrc32()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId();
    hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaId();
    hash = (37 * hash) + START_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartOffset());
    hash = (37 * hash) + END_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndOffset());
    hash = (37 * hash) + CRC32_FIELD_NUMBER;
    hash = (53 * hash) + getCrc32();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flux.sdk.proto.RawSegment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flux.sdk.proto.RawSegment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flux.sdk.proto.RawSegment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flux.sdk.proto.RawSegment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flux.sdk.proto.RawSegment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flux.wire.RawSegment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flux.wire.RawSegment)
      io.flux.sdk.proto.RawSegmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawSegment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawSegment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flux.sdk.proto.RawSegment.class, io.flux.sdk.proto.RawSegment.Builder.class);
    }

    // Construct using io.flux.sdk.proto.RawSegment.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topicId_ = 0;
      schemaId_ = 0;
      startOffset_ = 0L;
      endOffset_ = 0L;
      crc32_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flux.sdk.proto.FluxWire.internal_static_flux_wire_RawSegment_descriptor;
    }

    @java.lang.Override
    public io.flux.sdk.proto.RawSegment getDefaultInstanceForType() {
      return io.flux.sdk.proto.RawSegment.getDefaultInstance();
    }

    @java.lang.Override
    public io.flux.sdk.proto.RawSegment build() {
      io.flux.sdk.proto.RawSegment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flux.sdk.proto.RawSegment buildPartial() {
      io.flux.sdk.proto.RawSegment result = new io.flux.sdk.proto.RawSegment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.flux.sdk.proto.RawSegment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.topicId_ = topicId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.schemaId_ = schemaId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.startOffset_ = startOffset_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.endOffset_ = endOffset_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.crc32_ = crc32_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.payload_ = payload_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flux.sdk.proto.RawSegment) {
        return mergeFrom((io.flux.sdk.proto.RawSegment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flux.sdk.proto.RawSegment other) {
      if (other == io.flux.sdk.proto.RawSegment.getDefaultInstance()) return this;
      if (other.getTopicId() != 0) {
        setTopicId(other.getTopicId());
      }
      if (other.getSchemaId() != 0) {
        setSchemaId(other.getSchemaId());
      }
      if (other.getStartOffset() != 0L) {
        setStartOffset(other.getStartOffset());
      }
      if (other.getEndOffset() != 0L) {
        setEndOffset(other.getEndOffset());
      }
      if (other.getCrc32() != 0) {
        setCrc32(other.getCrc32());
      }
      if (!other.getPayload().isEmpty()) {
        setPayload(other.getPayload());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              topicId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              schemaId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              startOffset_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              endOffset_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              crc32_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int topicId_ ;
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return The topicId.
     */
    @java.lang.Override
    public int getTopicId() {
      return topicId_;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @param value The topicId to set.
     * @return This builder for chaining.
     */
    public Builder setTopicId(int value) {

      topicId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      topicId_ = 0;
      onChanged();
      return this;
    }

    private int schemaId_ ;
    /**
     * <code>uint32 schema_id = 2;</code>
     * @return The schemaId.
     */
    @java.lang.Override
    public int getSchemaId() {
      return schemaId_;
    }
    /**
     * <code>uint32 schema_id = 2;</code>
     * @param value The schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaId(int value) {

      schemaId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 schema_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      schemaId_ = 0;
      onChanged();
      return this;
    }

    private long startOffset_ ;
    /**
     * <code>uint64 start_offset = 3;</code>
     * @return The startOffset.
     */
    @java.lang.Override
    public long getStartOffset() {
      return startOffset_;
    }
    /**
     * <code>uint64 start_offset = 3;</code>
     * @param value The startOffset to set.
     * @return This builder for chaining.
     */
    public Builder setStartOffset(long value) {

      startOffset_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 start_offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartOffset() {
      bitField0_ = (bitField0_ & ~0x00000004);
      startOffset_ = 0L;
      onChanged();
      return this;
    }

    private long endOffset_ ;
    /**
     * <code>uint64 end_offset = 4;</code>
     * @return The endOffset.
     */
    @java.lang.Override
    public long getEndOffset() {
      return endOffset_;
    }
    /**
     * <code>uint64 end_offset = 4;</code>
     * @param value The endOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndOffset(long value) {

      endOffset_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 end_offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndOffset() {
      bitField0_ = (bitField0_ & ~0x00000008);
      endOffset_ = 0L;
      onChanged();
      return this;
    }

    private int crc32_ ;
    /**
     * <code>uint32 crc32 = 5;</code>
     * @return The crc32.
     */
    @java.lang.Override
    public int getCrc32() {
      return crc32_;
    }
    /**
     * <code>uint32 crc32 = 5;</code>
     * @param value The crc32 to set.
     * @return This builder for chaining.
     */
    public Builder setCrc32(int value) {

      crc32_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 crc32 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCrc32() {
      bitField0_ = (bitField0_ & ~0x00000010);
      crc32_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Compressed FL segment payload (zstd).
     * </pre>
     *
     * <code>bytes payload = 6;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * Compressed FL segment payload (zstd).
     * </pre>
     *
     * <code>bytes payload = 6;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Compressed FL segment payload (zstd).
     * </pre>
     *
     * <code>bytes payload = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000020);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flux.wire.RawSegment)
  }

  // @@protoc_insertion_point(class_scope:flux.wire.RawSegment)
  private static final io.flux.sdk.proto.RawSegment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flux.sdk.proto.RawSegment();
  }

  public static io.flux.sdk.proto.RawSegment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RawSegment>
      PARSER = new com.google.protobuf.AbstractParser<RawSegment>() {
    @java.lang.Override
    public RawSegment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RawSegment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RawSegment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flux.sdk.proto.RawSegment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

