// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

@com.google.protobuf.Generated
public interface ReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flux.wire.ReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>uint32 error_code = 2;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>repeated .flux.wire.TopicResult results = 4;</code>
   */
  java.util.List<io.flux.sdk.proto.TopicResult> 
      getResultsList();
  /**
   * <code>repeated .flux.wire.TopicResult results = 4;</code>
   */
  io.flux.sdk.proto.TopicResult getResults(int index);
  /**
   * <code>repeated .flux.wire.TopicResult results = 4;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .flux.wire.TopicResult results = 4;</code>
   */
  java.util.List<? extends io.flux.sdk.proto.TopicResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .flux.wire.TopicResult results = 4;</code>
   */
  io.flux.sdk.proto.TopicResultOrBuilder getResultsOrBuilder(
      int index);
}
