// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flux_wire.proto
// Protobuf Java Version: 4.33.4

package io.flux.sdk.proto;

@com.google.protobuf.Generated
public interface RecordBatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flux.wire.RecordBatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>uint32 schema_id = 2;</code>
   * @return The schemaId.
   */
  int getSchemaId();

  /**
   * <code>repeated .flux.wire.Record records = 3;</code>
   */
  java.util.List<io.flux.sdk.proto.Record> 
      getRecordsList();
  /**
   * <code>repeated .flux.wire.Record records = 3;</code>
   */
  io.flux.sdk.proto.Record getRecords(int index);
  /**
   * <code>repeated .flux.wire.Record records = 3;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .flux.wire.Record records = 3;</code>
   */
  java.util.List<? extends io.flux.sdk.proto.RecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .flux.wire.Record records = 3;</code>
   */
  io.flux.sdk.proto.RecordOrBuilder getRecordsOrBuilder(
      int index);
}
